/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#000000",
        "primary-container": "#0d1c33",
        "surface-variant": "#d9e3f4",
        "secondary-fixed": "#ffe088",
        "surface-tint": "#515f79",
        "secondary": "#735c00",
        "primary-fixed": "#d6e3ff",
        "on-tertiary-fixed-variant": "#444749",
        "secondary-container": "#fed65b",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#745c00",
        "tertiary-fixed": "#e1e2e4",
        "inverse-surface": "#27313e",
        "on-primary-fixed": "#0d1c33",
        "on-error": "#ffffff",
        "on-background": "#121c28",
        "on-primary-fixed-variant": "#394760",
        "on-tertiary-container": "#828486",
        "surface-container-low": "#eef4ff",
        "on-primary-container": "#7684a0",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "surface": "#f8f9ff",
        "surface-dim": "#d1dbec",
        "tertiary": "#000000",
        "outline": "#75777e",
        "tertiary-fixed-dim": "#c5c6c8",
        "inverse-on-surface": "#eaf1ff",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#241a00",
        "inverse-primary": "#b9c7e5",
        "surface-container-high": "#dfe9fa",
        "tertiary-container": "#191c1e",
        "on-tertiary-fixed": "#191c1e",
        "surface-bright": "#f8f9ff",
        "surface-container-highest": "#d9e3f4",
        "surface-container": "#e5eeff",
        "on-surface": "#121c28",
        "on-surface-variant": "#44474d",
        "on-primary": "#ffffff",
        "outline-variant": "#c5c6ce",
        "primary-fixed-dim": "#b9c7e5",
        "secondary-fixed-dim": "#e9c349",
        "on-tertiary": "#ffffff",
        "background": "#f8f9ff",
        "on-secondary-fixed-variant": "#574500",
        "on-error-container": "#93000a"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px"
      },
      spacing: {
        "stack-lg": "48px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        "stack-sm": "12px",
        "base": "8px",
        "stack-md": "24px",
        "container-max": "1280px",
        "gutter": "24px"
      },
      fontFamily: {
        "display-lg": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }]
      },
      boxShadow: {
        "soft": "0 4px 12px rgba(10, 25, 48, 0.04)",
        "hover": "0 8px 24px rgba(10, 25, 48, 0.08)",
        "glow": "0 0 0 2px rgba(10, 25, 48, 0.1)"
      }
    },
  },
  plugins: [],
}
